Description: 'AWS CloudFormation Template to create an Elastic Beanstalk environment.'
Parameters:
  VpcID:
    Description: Select the VPC for Elastic Beanstalk hosts.
    Type: "AWS::EC2::VPC::Id"

  InstanceKeyPair: 
    Description: Select the KeyPair for Elastic Beanstalk hosts.
    Type: "AWS::EC2::KeyPair::KeyName"

  InstanceSubnetID: 
    Description: Select the Subnet for Elastic Beanstalk host.
    Type: "AWS::EC2::Subnet::Id"

Resources:
  sampleApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      Description: AWS Elastic Beanstalk Sample Application

  sampleApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName:
        Ref: sampleApplication
      Description: AWS ElasticBeanstalk Node.js Sample Application Version
      SourceBundle:
        S3Bucket: !Sub "elasticbeanstalk-samples-${AWS::Region}"
        S3Key: nodejs-sample-v2.zip

  BeanstalkSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "beanstalk-sg"
      GroupDescription: "Allow the Elastic Beanstalk instances to access"
      VpcId:
        Ref: VpcID
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: '0'
        ToPort: '65535'
        CidrIp: 0.0.0.0/0

  sampleConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName:
        Ref: sampleApplication
      Description: AWS ElasticBeanstalk Sample Configuration Template
      OptionSettings:
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: SecurityGroups
        Value:
          Ref: BeanstalkSecurityGroup
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: EC2KeyName
        Value:
          Ref: InstanceKeyPair
      - Namespace: aws:ec2:vpc
        OptionName: VPCId
        Value:
          Ref: VpcID
      - Namespace: aws:ec2:vpc
        OptionName: Subnets
        Value:
          Ref: InstanceSubnetID
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: ServiceRole
        Value: aws-elasticbeanstalk-service-role
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value: aws-elasticbeanstalk-ec2-role
      SolutionStackName: 64bit Amazon Linux 2018.03 v4.5.3 running Node.js

  sampleEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName:
        Ref: sampleApplication
      Description: AWS ElasticBeanstalk Node.js Sample Environment
      TemplateName:
        Ref: sampleConfigurationTemplate
      VersionLabel:
        Ref: sampleApplicationVersion

Outputs:
  URL:
    Description: The URL of the Elastic Beanstalk environment
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt:
          - sampleEnvironment
          - EndpointURL      